project:
  type: website
  output-dir: docs

website:
  title: "Rob's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/FranklinTheTank
format:
  html:
    theme: cyborg
    css: styles.css

editor: visual

